name: StrawKits
main: bzh.strawberry.kits.StrawKits
version: ${project.version}
author: Eclixal
api-version: 1.16
website: https://strawberry.bzh
description: Help you to create Kits on your server
commands:
  kit:
    aliases: [kits]
    description: Open the GUI selector
    usage: Usage /kit or /kits